version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: rzhkv/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: rzhkv/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
        - static:/frontend_static
  gateway:
    image: rzhkv/foodgram_gateway
    volumes:
      - static:/static
      - media:/media
    ports:
      - 7000:80
    depends_on:
      - backend
      - frontend