# Generated by Django 3.2 on 2024-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241008_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/recipes_images', verbose_name='Изображение рецепта'),
        ),
    ]
